empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'lista-todo-empleados/', 
        views.listAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>', 
        views.listByAreaEmpleados.as_view(),
        name="empleados_area"
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name="empleados_admin"
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListaHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detail"
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/', 
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empeado'
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.persona.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

empleado/applications/persona/models.py
from django.db import models
from django.db.models.base import Model
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

class Habiliades(models.Model):
    Habilidad = models.CharField('Habilidad',max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return  str(self.id) + '-' + self.Habilidad 
    

# Create your models here.
class Empleado(models.Model):
    """ Modelo para tabla empleados"""
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )
    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellido', max_length=50)
    full_name = models.CharField(
        'Nombre Completo', 
        max_length=50,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=1,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField( upload_to='empleado', height_field=None, width_field=None, max_length=None, blank=True)
    habilidades = models.ManyToManyField(Habiliades)

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name
    

empleado/applications/persona/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """EmpleadoForm definition."""
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'image',
            'habilidades',
        )

        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(
                
            )
        }

empleado/applications/persona/views.py
from django.db.models.fields import files
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (     
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
# Create your views here.

from .models import Empleado
from .forms import EmpleadoForm

class InicioView(TemplateView):
    template_name = "inicio.html"

class listAllEmpleados(ListView):
    template_name = 'persona/lista_all.html'
    paginate_by = 4
    ordering = "first_name"
    # model = Empleado
    # context_object_name = 'lista'

    
    def get_queryset(self):       
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            full_name__icontains = palabra_clave
        )
        return lista


class listByAreaEmpleados(ListView):
    template_name = "persona/lista_by_area.html"
    context_object_name = "empleados"

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__name = area
        )
        return lista

        
class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = "id"
    # model = Empleado
    context_object_name = 'empleados'
    model = Empleado


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):       
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        return lista

class ListaHabilidadesEmpleado(ListView):
    template_name = 'persona/habiliades.html'
    context_object_name = 'habiliadades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id = 15)
        return empleado.habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona\detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context
        

class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    # fields = [
    #     'first_name',
    #     'last_name', 
    #     'job',
    #     'departamento',
    #     'habilidades',
    #     'image',
    # ]
    form_class = EmpleadoForm
    # fields = ('__all__')
    success_url = reverse_lazy('persona_app:correcto') 

    def form_valid(self, form):
        empleado = form.save()
        empleado.full_name = empleado.first_name = ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name', 
        'job',
        'departamento',
        'habilidades',
    ]
    # success_url = reverse_lazy('persona_app:correcto') 
    success_url = reverse_lazy('persona_app:empleados_admin') 

    def post(self, request, *args, **kwargs) :
        self.object = self.get_object()
        # print(request.POST)
        # print(request.POST['first_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(EmpleadoUpdateView, self).form_valid(form)



class EmpleadoDeleteView(DeleteView):
    template_name = "persona/delete.html"
    model = Empleado
    # success_url = reverse_lazy('persona_app:correcto') 
    success_url = reverse_lazy('persona_app:empleados_admin') 

empleado/templates/persona/add.html
{% extends "base.html" %}

{% block title %}
  
{% endblock title %}

{% block content %}
{% include "includes\header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" >Registrar personas </h1>        
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %} 
            <div class="medium-6 cell">
                <label> Nombres:
                    {{ form.first_name }}
                </label>
            </div>       
            <div class="medium-6 cell">
                <label> Apellidos:
                    {{ form.last_name }}
                </label>
            </div>       
            <div class="medium-6 cell">
                <label> Trabajo:
                    {{ form.job }}
                </label>
            </div>       
            <div class="medium-6 cell">
                <label> Departamentos:
                    {{ form.departamento }}
                </label>
            </div>        
            <div class="medium-6 cell">
                <label> Habilidades:
                    {{ form.habilidades }}
                </label>
            </div>     
            <div class="medium-6 cell">
                <label> Habilidades:
                    {{ form.image }}
                </label>
            </div>         
            <div class="medium-12 cell">
                <button class="button success" type="submit">Agregar</button>              
            </div>   
        </form>        
    </div>
</div>
  
{% endblock content %}

empleado/templates/persona/by_kword.html
<h1>Buscar Empleado por palabra</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for item in empleados %}
        <li>{{item}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/delete.html
{% extends "base.html" %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar Empleado: {{object.full_name}} </h1>
            <form class="cell" method="POST"> {% csrf_token %}
                <div class="callout secondary">
                    <h5>¿Desea eliminar a este empleado?</h5>
                    <button class="alert button" type="submit">Confirmar</button>
                  </div>
            
            </form>
            
        </div>
    </div>
    
{% endblock content %}

empleado/templates/persona/detail_empleado.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{object.full_name}}
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell large-4 card" style="width: 300px;">
                <div class="card-divider">
                  {{empleado.get_gob_display}}
                </div>
                
                {% if empleado.image %}                    
                    <img src="{{empleado.image.url}}">
                {% else %}   
                    <img src="{% static 'img/20.png' %}">
                {% endif %}
                    
                <div class="card-section">
                   <h4>{{empleado.full_name}}</h4>
                   <p>{{empleado.last_name}}</p>
                   <p>{{empleado.departamento.shor_name}}</p>
                   <p><span class="label">Habilidades:</span></p>
                   <ul class="vertical menu">
                       
                       {% for h in empleado.habilidades.all %}
                           <li>{{h.Habilidad}}</li>
                       {% endfor %}
                           
                   </ul>
                </div>
              </div>
        </div>
    </div>
{% endblock content %}
<!-- 
<h1>Detalle de un Empleado {{titulo}}</h1>

{{empleado}}


<h1>{{empleado.first_name}}</h1>
<h1>{{empleado.last_name}}</h1>
<h1>{{empleado.job}}</h1>
<h1>{{empleado.departamento}}</h1>
<h1>{{empleado.image}}</h1>
<h1>{{empleado.habilidades}}</h1> -->

empleado/templates/persona/habiliades.html
<h1>Habilidades de empleados</h1>
<ul>
    
    {% for item in habiliadades %}
        <li>{{item}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/lista_all.html
{% extends "base.html" %} 
{% block content %} 
{% include "includes\header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">lista Empleados</h1>
    <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
      <div class="cell large-7">
        <input type="text" id="kword" name="kword" placeholder="Buscar Empleado" />
      </div>
      <div class="cell large-2">
        <button type="submit" class="success button">Save</button>
      </div>
    </form>
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th >Nombres</th>
            <th width="150">Apellidos</th>
            <th width="150">Departamentos</th>
            <th width="150">Accion</th>
          </tr>
        </thead>
        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.id}}</td>
            <td>{{item.first_name}}</td>
            <td>{{item.last_name}}</td>
            <td>{{item.departamento}}</td>
            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' item.id %}">Ver</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}" aria-label="Page {{page_obj.previous_page_number}}">Atras</a>
                        </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}
                        
                        {% ifequal pagina page_obj.number %} 
                            <li class="current"><span class="show-for-sr">Tu pagina</span>{{pagina}}</a></li>  
                        {% else %}
                            <li><a href="?page={{pagina}}" aria-label="Page {{pagina}}">{{pagina}}</a></li>  
                        {% endifequal %}
                                                  
                    {% endfor %}
                        
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}" aria-label="Page {{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </nav>
    </div>
  </div>
</div>

{% endblock content %}

empleado/templates/persona/lista_by_area.html
{% extends "base.html" %} 
{% block title %} lista empleados por departamento {%endblock title %} 
{% block content %} 
{% include "includes/header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>Nombres</th>
            <th width="150">Apellidos</th>
            <th width="150">Departamentos</th>
            <th width="150">Accion</th>
          </tr>
        </thead>
        <tbody>
          {% for item in empleados %}
          <tr>
            <td>{{item.id}}</td>
            <td>{{item.first_name}}</td>
            <td>{{item.last_name}}</td>
            <td>{{item.departamento}}</td>
            <td>
              <a
                class="button warning"
                href="{% url 'persona_app:empleado_detail' item.id %}"
                >Ver</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

empleado/templates/persona/lista_empleados.html
{% extends "base.html" %} 
{% block content %} 
{% include "includes\header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">lista Empleados</h1>
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th >Nombres</th>
            <th width="150">Apellidos</th>
            <th width="150">Departamentos</th>
            <th width="150">Editar</th>
            <th width="150">Eliminar</th>
          </tr>
        </thead>
        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.id}}</td>
            <td>{{item.first_name}}</td>
            <td>{{item.last_name}}</td>
            <td>{{item.departamento}}</td>
            <td>
                <a class="button success" href="{% url 'persona_app:modificar_empleado' item.id %}">Editar</a>
            </td>
            <td>
                <a class="button alert" href="{% url 'persona_app:eliminar_empeado' item.id %}">Eliminar</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}" aria-label="Page {{page_obj.previous_page_number}}">Atras</a>
                        </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}
                        
                        {% ifequal pagina page_obj.number %} 
                            <li class="current"><span class="show-for-sr">Tu pagina</span>{{pagina}}</a></li>  
                        {% else %}
                            <li><a href="?page={{pagina}}" aria-label="Page {{pagina}}">{{pagina}}</a></li>  
                        {% endifequal %}
                                                  
                    {% endfor %}
                        
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}" aria-label="Page {{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </nav>
    </div>
  </div>
</div>

{% endblock content %}

empleado/templates/persona/success.html
<h1>Se cre correctamente el empleado</h1>

empleado/templates/persona/update.html
{% extends "base.html" %}

{% block title %}
  
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Modificar Empleado
            </h1>
            <div class="cell">                
                <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                    <div class="cell large-6">
                        <label>Nombres:
                            {{form.first_name}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Apellidos:
                            {{form.last_name}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Trabajo:
                            {{form.job}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Area:
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Habilidades Extra:
                            {{form.habilidades}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>   
{% endblock content %}