empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

# def DesdeApps(self):
#     print('=========HOLA LA APP DEPARTAMENTOS=========')

app_name = "departamento_app"

urlpatterns = [
    # path('departamento/', DesdeApps),
    path(
        'departamento-list/', 
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),
    path('new-departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento')
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'lista-todo-empleados/', 
        views.listAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>', 
        views.listByAreaEmpleados.as_view(),
        name="empleados_area"
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name="empleados_admin"
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListaHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detail"
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/', 
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empeado'
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.persona.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50,blank=True)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la Empresa'
        ordering = ['-name']
        unique_together = ('name','shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    """NewDepartamentoForm definition."""
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

    # TODO: Define form fields here

empleado/applications/departamento/views.py
from django import forms
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from applications.persona import models

from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm

class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = "departamentos"

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        depa.save()

        nombre  = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            job = '1',
            departamento = depa
        )

        return super(NewDepartamentoView, self).form_valid(form)

# Create your views here.

empleado/templates/departamento/lista.html
{% extends "base.html" %}

{% block title %}
  Lista departamentos
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                <table>
                    <tbody>                        
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{departamento.name}}</td>
                                <td>{{departamento.shor_name}}</td>
                                <td>
                                    <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                                </td>
                            </tr>
                        {% endfor %}                            
                    </tbody>
                </table>
            </h1>
        </div>
    </div>
{% endblock content %}

empleado/templates/departamento/new_departamento.html
{% extends "base.html" %}

{% block title %}
  
{% endblock title %}

{% block content %}
    {% include "includes\header.html" %}
    <div class="grid-x">
        <div class="grid-x">
            <h1 class="cell">                
                <form class="cell callout grid-x grid-margin-x" method="POST"> {% csrf_token %}
                    <h3 class="medium-12 cell" >Datos Empleado</h3>
                    <div class="medium-6 cell">
                        <label>Nombre:
                            {{form.nombre}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Apellidos:
                            {{form.apellidos}}
                        </label>
                    </div>
                    <h3 class="medium-12 cell" >Datos Departamento</h3>
                    <div class="medium-6 cell">
                        <label>Departamento:
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Nombre Corto:
                            {{form.shorname}}
                        </label>
                    </div>
                    <div class="medium-12 cell">
                        <button class="button success" type="submit">Guardar</button>
                    </div>
                </form>
            </h1>
        </div>
    </div>
{% endblock content %}

<h1>Nuevo Departamento</h1>